version: '3.8'

services:
  # Redis para caché
  redis:
    image: redis:7-alpine
    container_name: 4gmovil-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    networks:
      - 4gmovil-network

  # Redis Commander (opcional - interfaz web)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: 4gmovil-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=${REDIS_COMMANDER_USER:-admin}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD:-admin}
    depends_on:
      - redis
    networks:
      - 4gmovil-network

volumes:
  redis_data:
    driver: local

networks:
  4gmovil-network:
    driver: bridge
