services:
  - type: web
    name: laravel-app
    env: docker
    plan: free   # o starter/pro según lo que uses en Render
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false   # ⚠️ genera el APP_KEY en tu máquina con `php artisan key:generate --show` y cópialo en Render
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password

    buildCommand: |
      composer install --no-dev --optimize-autoloader --no-scripts
      npm install
      npm run build || echo "⚠️ Sin build de assets (si no usas Vite/React ignora este aviso)"
    
startCommand: |
  mkdir -p storage/framework/{cache,sessions,views}
  touch storage/logs/laravel.log
  chmod -R 777 storage bootstrap/cache
  php artisan config:clear
  php artisan cache:clear
  php artisan route:clear
  php artisan view:clear
  php artisan migrate --force
  apache2-foreground




databases:
  - name: laravel-db
    plan: free
    databaseName: db_4gmovil
    user: db_4gmovil_user
